# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.3.0
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:18.4.0-browsers
  resource_class: small
jobs:
  build_and_test:
    <<: *defaults
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: sync and update submodules
          command: git submodule sync --recursive && git submodule update --recursive --init
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm run test
      - run:
          name: build
          command: |
            if [ $CIRCLE_BRANCH = 'main' ]; then
              npm run build-engx-rt
            fi
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo
      - run:
          name: Publish to NPM
          command: |
            if [ $CIRCLE_BRANCH = 'main' ]; then
              npm run publish-engx-rt
            fi
workflows:
  version: 2
  build_test_and_publish_on_version_increment:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - main
      - publish:
          requires:
            - build_and_test
          filters:
            tags:
              only: /v(\d+\.)?(\d+\.)?(\*|\d+)$/
            branches:
              ignore: /.*/
