# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.3.0
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.4.0-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: sync and update submodules
          command: git submodule sync --recursive && git submodule update --recursive --init
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm run test
      - run:
          name: build
          command: |
            if [ $CIRCLE_BRANCH = 'main' ]; then
              npm run build-engx-rt
            fi
      - run:
          name: publish to npm
          command: |
            if [ $CIRCLE_BRANCH = 'main' ]; then
              npm run publish-engx-rt
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish:
    docker:
      - image: cimg/node:18.4.0-browsers
    steps:
      - run:
          name: Publish to NPM
          command: npm run publish-engx-rt
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              only: main